### ISSUE TITLE
[epic] Wallet SignUp/SignIn

### ISSUE THREAD

**Issue by rolsonquadras** [trustbloc/wallet#1363]
- [x] https://github.com/trustbloc/wallet/issues/1358
- [x] https://github.com/trustbloc/wallet/issues/1362
- [x] https://github.com/trustbloc/wallet/issues/1361
