### ISSUE TITLE
Credential Manifest

### ISSUE THREAD

**Issue by sudeshrshetty** [trustbloc/wallet#1398]
- [x] support for credential manifest in aries vc wallet : https://github.com/hyperledger/aries-framework-go/issues/3120
- [x] wallet JS SDK 
  - [x] APIs for credential manifest data model, mapping, persistence and descriptor map https://github.com/trustbloc/wallet/issues/1421
  - [x] support for credential manifest in wallet queries including WACI https://github.com/trustbloc/wallet/issues/1422
- [x] wallet
  - [x]  credential manifest support in credential save  https://github.com/trustbloc/wallet/issues/1462
  - [x] credential manifest support in credential preview (wallet credentials screen, save, share credentials) https://github.com/trustbloc/wallet/issues/1424
