### ISSUE TITLE
CHAPI bridge

### ISSUE THREAD

**Issue by sudeshrshetty** [trustbloc/wallet#633]
Design: 
![image](https://user-images.githubusercontent.com/29631944/105557014-3f06c900-5cd9-11eb-95c6-fb33446a0a6d.png)

**Tasks:**

**Browser API for issuer/verifiers**
- [x] Request connection invitation redirect URL
- [x] Request, save wallet profile
- [x] Request CHAPI response
- [x] Wallet profile recovery

**Wallet Server** (Moved to adapter: https://github.com/trustbloc/edge-adapter/issues/425)
- [x] Open API support #635
- [x] Wallet server as agent #637
- [x] chapi-bridge interfaces in wallet server #636 
- [x] Create connection invitation #646
- [x] Create wallet profile on did-exchange complete #650
- [x] Handle CHAPI request #652
- [x] Query wallet profile  #650
- [x] Wallet profile recovery  #650
- [x] Message handle for CHAPI response DIDcomm message  #652
- [x] Retry/Await on app profile request #654

**Mediator API**
- [x] Message handle for CHAPI request DIDcomm message
- [ ] ~~Push notification API~~

**Mobile binding APIs**
- [x] Send CHAPI response
- [x] Receive CHAPI request(if required)

**Integration in Demo**
- [x] update edge-sandbox demo

**BDD tests**
- [x] wallet server tests - https://github.com/trustbloc/edge-adapter/issues/418, https://github.com/trustbloc/edge-adapter/issues/417
- [x] agent-sdk tests

**Documentation**
- [ ] ~~update demo docs~~
- [ ] ~~update trustbloc docs~~

**Wallet bridge serve & UI in edge-adapters**

- [x] https://github.com/trustbloc/edge-adapter/issues/425

**Universal Wallet 2020**
- [x] push wallet server interfaces to universal wallet 2020 interop. (Not needed)

Follow up:
- [ ] ~~managing wallet app URLs #645~~
- [x] migrate CHAPI bridge as app-bridge in adapters #651 & https://github.com/trustbloc/edge-adapter/issues/413

**Comment by sudeshrshetty** [comment]
To be covered as part of Wallet selector APIs
